import { TriggerContext } from '@devvit/public-api';
import { TRACKED_ACTIONS, ACTION_LABELS } from './constants.js';
import {
  keyActionCount,
  keyModCount,
  keyTargetCount,
  keyDailyCount,
  keyRecentActions,
  getCount,
  getKeysWithPrefix,
} from './redisHelper.js';
import { formatUsername } from './utility.js';

interface WikiOptions {
  yearEnd?: boolean;
}

export async function generateModStatsWiki(
  context: TriggerContext,
  options: WikiOptions = {}
): Promise<void> {
  const now = new Date();
  const year = now.getUTCFullYear();
  const month = now.getUTCMonth() + 1;
  const { redis, reddit, settings } = context;

  const topN = ((await settings.get('topNTargets')) as number) || 5;
  const recentCount = ((await settings.get('recentActionsCount')) as number) || 20;
  const modOnly = ((await settings.get('modOnly')) as boolean) ?? true;

  const subreddit = await reddit.getCurrentSubreddit();
  const subName = subreddit.name;

  let md = `# Moderation Insights — ${monthName(month)} ${year}\n\n`;
  md += `*Auto-generated by [mod-stats](https://github.com/loamyx/mod-stats). `;
  md += `Last updated: ${now.toISOString()}*\n\n`;

  md += `## Action Summary\n\n`;
  md += `| Action | Count |\n|---|---|\n`;
  let totalActions = 0;
  for (const action of TRACKED_ACTIONS) {
    const count = await getCount(redis, keyActionCount(year, month, action));
    if (count > 0) {
      md += `| ${ACTION_LABELS[action] || action} | ${count} |\n`;
      totalActions += count;
    }
  }
  md += `| **Total** | **${totalActions}** |\n\n`;

  md += `## Top Moderators\n\n`;
  const modKeys = await getKeysWithPrefix(redis, `mod-stats:mods:${year}-${String(month).padStart(2, '0')}:`);
  const modCounts: { name: string; count: number }[] = [];
  for (const key of modKeys) {
    const name = key.split(':').pop() || '';
    const count = await getCount(redis, key);
    modCounts.push({ name, count });
  }
  modCounts.sort((a, b) => b.count - a.count);
  md += `| Moderator | Actions |\n|---|---|\n`;
  for (const mod of modCounts) {
    md += `| ${formatUsername(mod.name)} | ${mod.count} |\n`;
  }
  md += `\n`;

  md += `## Top Targeted Users\n\n`;
  const targetKeys = await getKeysWithPrefix(redis, `mod-stats:targets:${year}-${String(month).padStart(2, '0')}:`);
  const targetCounts: { name: string; count: number }[] = [];
  for (const key of targetKeys) {
    const name = key.split(':').pop() || '';
    const count = await getCount(redis, key);
    targetCounts.push({ name, count });
  }
  targetCounts.sort((a, b) => b.count - a.count);
  md += `| User | Times Actioned |\n|---|---|\n`;
  for (const target of targetCounts.slice(0, topN)) {
    md += `| ${formatUsername(target.name)} | ${target.count} |\n`;
  }
  md += `\n`;

  md += `## Daily Activity\n\n`;
  const daysInMonth = new Date(year, month, 0).getDate();
  md += `| Day | Actions |\n|---|---|\n`;
  for (let d = 1; d <= daysInMonth; d++) {
    const count = await getCount(redis, keyDailyCount(year, month, d));
    if (count > 0) {
      md += `| ${String(d).padStart(2, '0')} | ${count} |\n`;
    }
  }
  md += `\n`;

  md += `## Recent Actions\n\n`;
  const recentRaw = await redis.get(keyRecentActions(year, month));
  const recentList = recentRaw ? JSON.parse(recentRaw) : [];
  md += `| Time | Moderator | Action | Target |\n|---|---|---|---|\n`;
  for (const entry of recentList.slice(0, recentCount)) {
    const time = entry.timestamp ? new Date(entry.timestamp).toUTCString() : '';
    md += `| ${time} | ${formatUsername(entry.moderator)} | ${ACTION_LABELS[entry.actionType] || entry.actionType} | ${formatUsername(entry.target)} |\n`;
  }
  md += `\n`;

  const pageName = `mod-stats/${year}-${String(month).padStart(2, '0')}`;
  try {
    await reddit.getWikiPage(subName, pageName);
    await reddit.updateWikiPage({
      subredditName: subName,
      page: pageName,
      content: md,
      reason: `mod-stats auto-update ${now.toISOString()}`,
    });
  } catch {
    await reddit.createWikiPage({
      subredditName: subName,
      page: pageName,
      content: md,
      reason: `mod-stats initial creation`,
    });
  }

  if (modOnly) {
    await reddit.updateWikiPageSettings({
      subredditName: subName,
      page: pageName,
      listed: false,
      permLevel: 2,
    });
  }

  console.log(`[mod-stats] Wiki page updated: ${pageName}`);
}

function monthName(m: number): string {
  return ['', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'][m];
}
