import { TriggerContext } from "@devvit/public-api";
import { ACTION_LABELS, TRACKED_ACTIONS } from "./constants.js";
import {
  keyLeaderboard,
  keyActionCounts,
  keyDailyCounts,
  keyTargetCounts,
  getTopMembers,
} from "./redisHelper.js";
import { formatUsername } from "./utility.js";

export async function generateModStatsWiki(
  context: TriggerContext
): Promise<void> {
  const { redis, reddit, settings } = context;
  const subreddit = await reddit.getCurrentSubreddit();

  const topN = ((await settings.get("wikiTopN")) as number) ?? 10;
  const wikiPage = ((await settings.get("wikiPageName")) as string) ?? "mod-stats";

  const now = new Date();
  const year = now.getUTCFullYear();
  const month = now.getUTCMonth() + 1;
  const monthStr = `${year}-${String(month).padStart(2, "0")}`;

  const lines: string[] = [
    `# Moderation Statistics \u2014 ${monthStr}`,
    "",
    `> Last updated: ${now.toISOString()}`,
    "",
  ];

  const topMods = await getTopMembers(redis, keyLeaderboard(year, month), topN);
  if (topMods.length > 0) {
    lines.push("## Top Moderators");
    lines.push("");
    lines.push("| Rank | Moderator | Actions |");
    lines.push("|------|-----------|---------||");
    topMods.forEach((entry, idx) => {
      lines.push(
        `| ${idx + 1} | ${formatUsername(entry.member)} | ${entry.score} |`
      );
    });
    lines.push("");
  }

  const topActions = await getTopMembers(
    redis,
    keyActionCounts(year, month),
    TRACKED_ACTIONS.length
  );
  if (topActions.length > 0) {
    lines.push("## Action Breakdown");
    lines.push("");
    lines.push("| Action | Count |");
    lines.push("|--------|-------|");
    for (const entry of topActions) {
      const label = ACTION_LABELS[entry.member] ?? entry.member;
      lines.push(`| ${label} | ${entry.score} |`);
    }
    lines.push("");
  }

  const topTargets = await getTopMembers(redis, keyTargetCounts(year, month), topN);
  if (topTargets.length > 0) {
    lines.push("## Most Actioned Users");
    lines.push("");
    lines.push("| User | Times Actioned |");
    lines.push("|------|----------------|");
    for (const entry of topTargets) {
      lines.push(`| ${formatUsername(entry.member)} | ${entry.score} |`);
    }
    lines.push("");
  }

  const dailyData = await getTopMembers(redis, keyDailyCounts(year, month), 31);
  if (dailyData.length > 0) {
    lines.push("## Daily Activity");
    lines.push("");
    lines.push("| Day | Actions |");
    lines.push("|-----|---------||");
    const sorted = [...dailyData].sort((a, b) => a.member.localeCompare(b.member));
    for (const entry of sorted) {
      lines.push(`| ${monthStr}-${entry.member} | ${entry.score} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by mod-stats*");

  const content = lines.join("\n");

  try {
    await reddit.wiki.getPage(subreddit.name, wikiPage);
    await reddit.wiki.update(subreddit.name, wikiPage, content, "Auto-update mod stats");
  } catch {
    await reddit.wiki.update(subreddit.name, wikiPage, content, "Initial mod stats page");
  }

  console.log(`[mod-stats] Wiki page "${wikiPage}" updated for r/${subreddit.name}`);
}
